export const MEDICINES = [
  {
    id: 1,
    name: "Paracetamol 500mg",
    brand: "Panadol",
    category: "Analgesics",
    stock: 4,
    reorderPoint: 10,
    maxStock: 100,
    dailyVelocity: 3.2,
    unitCost: 0.25,
    sellingPrice: 0.5,
    unit: "tablets",
    batchId: "PAR-2025-001",
    expiryDate: "2026-12-31",
    supplierId: 1,
    isEssential: true,
    requiresPrescription: false,
    movements: [-3, -4, -2, -3, -5, -2, -3]
  },
  {
    id: 2,
    name: "Amoxicillin 250mg",
    brand: "Amoxil",
    category: "Antibiotics",
    stock: 45,
    reorderPoint: 15,
    maxStock: 80,
    dailyVelocity: 1.8,
    unitCost: 1.5,
    sellingPrice: 3.0,
    unit: "capsules",
    batchId: "AMX-2025-002",
    expiryDate: "2026-08-31",
    supplierId: 1,
    isEssential: true,
    requiresPrescription: true,
    movements: [-2, -1, -2, -2, -1, -3, -1]
  },
  {
    id: 3,
    name: "Artemether 20mg",
    brand: "Coartem",
    category: "Antimalarials",
    stock: 8,
    reorderPoint: 20,
    maxStock: 120,
    dailyVelocity: 4.1,
    unitCost: 2.8,
    sellingPrice: 5.5,
    unit: "tablets",
    batchId: "ART-2025-003",
    expiryDate: "2025-05-15",
    supplierId: 2,
    isEssential: true,
    requiresPrescription: true,
    movements: [-4, -5, -3, -4, -6, -4, -3]
  },
  {
    id: 4,
    name: "Ibuprofen 400mg",
    brand: "Brufen",
    category: "Anti-inflammatory",
    stock: 62,
    reorderPoint: 12,
    maxStock: 60,
    dailyVelocity: 2.1,
    unitCost: 0.75,
    sellingPrice: 1.5,
    unit: "tablets",
    batchId: "IBU-2025-004",
    expiryDate: "2025-04-30",
    supplierId: 1,
    isEssential: true,
    requiresPrescription: false,
    movements: [-2, -3, -1, -2, -2, -2, -3]
  },
  {
    id: 5,
    name: "ORS Sachets",
    brand: "WHO-ORS",
    category: "Rehydration",
    stock: 120,
    reorderPoint: 30,
    maxStock: 200,
    dailyVelocity: 5.5,
    unitCost: 0.15,
    sellingPrice: 0.35,
    unit: "sachets",
    batchId: "ORS-2025-005",
    expiryDate: "2027-03-31",
    supplierId: 2,
    isEssential: true,
    requiresPrescription: false,
    movements: [-6, -5, -7, -4, -6, -5, -6]
  },
  {
    id: 6,
    name: "Metformin 500mg",
    brand: "Glucophage",
    category: "Diabetes",
    stock: 28,
    reorderPoint: 20,
    maxStock: 80,
    dailyVelocity: 2.8,
    unitCost: 0.9,
    sellingPrice: 1.8,
    unit: "tablets",
    batchId: "MET-2025-006",
    expiryDate: "2026-11-30",
    supplierId: 1,
    isEssential: true,
    requiresPrescription: true,
    movements: [-3, -2, -3, -3, -2, -3, -3]
  },
  {
    id: 7,
    name: "Zinc Sulfate 20mg",
    brand: "Zinc-ORS",
    category: "Supplements",
    stock: 3,
    reorderPoint: 15,
    maxStock: 80,
    dailyVelocity: 3.0,
    unitCost: 0.2,
    sellingPrice: 0.45,
    unit: "tablets",
    batchId: "ZNC-2025-007",
    expiryDate: "2026-06-30",
    supplierId: 2,
    isEssential: true,
    requiresPrescription: false,
    movements: [-3, -3, -3, -2, -3, -3, -3]
  },
  {
    id: 8,
    name: "Chloroquine 150mg",
    brand: "Nivaquine",
    category: "Antimalarials",
    stock: 35,
    reorderPoint: 25,
    maxStock: 100,
    dailyVelocity: 1.5,
    unitCost: 0.6,
    sellingPrice: 1.2,
    unit: "tablets",
    batchId: "CLQ-2025-008",
    expiryDate: "2026-09-30",
    supplierId: 1,
    isEssential: true,
    requiresPrescription: true,
    movements: [-2, -1, -2, -1, -2, -1, -2]
  }
];

