import type { Insight } from "./insights";

export function buildAnalyticsReportText(medicines: any[], customers: any[], insights: Insight[]) {
  const date = new Date().toLocaleDateString("en-US", { day: "numeric", month: "long", year: "numeric" });
  const lines = [
    `NEVOUTMEDS — ANALYTICS REPORT`,
    `Monrovia Central Pharmacy`,
    `Generated: ${date}`,
    ``,
    `═══════════════════════════════════════`,
    `EXECUTIVE SUMMARY`,
    `═══════════════════════════════════════`,
    `Monthly Revenue: $4,820 (↑22% YoY)`,
    `Net Profit: $2,680 (55.6% margin)`,
    `Cash on Hand: $3,240`,
    `Total Inventory Value: $${medicines.reduce((s, m) => s + m.stock * m.unitCost, 0).toFixed(2)}`,
    `Active Customers: ${customers.length}`,
    `Outstanding Credit: $${customers.reduce((s, c) => s + c.creditBalance, 0).toFixed(2)}`,
    ``,
    `═══════════════════════════════════════`,
    `INSIGHTS & RECOMMENDATIONS (${insights.length} total)`,
    `═══════════════════════════════════════`,
    ...insights.map((ins, i) =>
      [
        ``,
        `[${ins.type.toUpperCase()}] ${i + 1}. ${ins.title}`,
        `Category: ${ins.category}`,
        ``,
        `WHAT IS HAPPENING:`,
        ins.detail,
        ``,
        `HOW IT AFFECTS YOUR FINANCIALS:`,
        ins.financial,
        ``,
        `RECOMMENDED ACTION:`,
        ins.recommendation,
        `───────────────────────────────────────`
      ].join("\n")
    ),
    ``,
    `═══════════════════════════════════════`,
    `INVENTORY STATUS`,
    `═══════════════════════════════════════`,
    ...medicines.map((m) => `${m.name}: ${m.stock} units · ${m.dailyVelocity}/day · Expires ${m.expiryDate}`),
    ``,
    `═══════════════════════════════════════`,
    `CUSTOMER CREDIT SUMMARY`,
    `═══════════════════════════════════════`,
    ...customers
      .filter((c) => c.creditBalance > 0)
      .map((c) => `${c.firstName} ${c.lastName} (${c.phone}): $${c.creditBalance.toFixed(2)} outstanding`),
    ``,
    `─────────────────────────────────────────`,
    `Report generated by Nevoutmeds Platform`,
    `Never Out of Stock · nevoutmeds.com`
  ];
  return lines.join("\n");
}

export function buildAnalyticsCsv(medicines: any[], customers: any[]) {
  const rows = [
    ["Metric", "Value", "Notes"],
    ["Monthly Revenue", "$4,820", "April 2026"],
    ["Net Profit", "$2,680", "55.6% margin"],
    ["Cash on Hand", "$3,240", ""],
    ["Outstanding Debt", "$2,800", "$350 overdue"],
    ["Customer Credit Out", "$" + customers.reduce((s, c) => s + c.creditBalance, 0).toFixed(2), ""],
    ...medicines.map((m) => ["Stock: " + m.name, m.stock + " units", m.dailyVelocity + "/day velocity"])
  ];
  return rows.map((r) => r.map((v) => `"${v}"`).join(",")).join("\n");
}

